dist: xenial

jobs:
  include:
    - stage: build proxy
      script:
        - docker build -t freecodecamp-proxy  -f Dockerfile.proxy .
    - stage: build api
      script:
        - docker build -t freecodecamp-api  -f Dockerfile.freecodecamp .
