dist: xenial

jobs:
  include:
    - stage: build api docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t freecodecamp-api-with-proxy .
      - docker images
      - docker tag freecodecamp-api-with-proxy $DOCKER_USERNAME/freecodecamp-api-with-proxy
      - docker push $DOCKER_USERNAME/freecodecamp-api-with-proxy