dist: xenial

jobs:
  include:
    - stage: build proxy
      script:
        - docker build -t freecodecamp-proxy  -f Dockerfile.proxy .
    - stage: build api
      script:
        - cd freecodecamp
        - npm install
        - node tools/scripts/ensure-path-migration-map.js
        - cd api-server
        - npm run build
        - cd $TRAVIS_BUILD_DIR
        - docker build -t freecodecamp-api  -f Dockerfile.freecodecamp .
