dist: xenial

jobs:
  include:
    - stage: build proxy
      if: branch != master
      script:
        - docker build -t freecodecamp-proxy  -f Dockerfile.proxy .
    - stage: build api
      if: branch != master
      script:
        - docker build -t freecodecamp-api  -f Dockerfile.freecodecamp .


    - stage: build=>deploy proxy
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t freecodecamp-proxy  -f Dockerfile.proxy .
        - docker images
        - docker tag freecodecamp-proxy freecodecamp/freecodecamp-proxy
        - docker push freecodecamp/freecodecamp-proxy
    - stage: build=>deploy api
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t freecodecamp-api  -f Dockerfile.freecodecamp .
        - docker images
        - docker tag freecodecamp-api freecodecamp/freecodecamp-api
        - docker push freecodecamp/freecodecamp-api
