dist: xenial

jobs:
  include:
    - stage: build proxy docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t freecodecamp-proxy . -f Dockerfile.proxy
      - docker images
      - docker tag freecodecamp-proxy $DOCKER_USERNAME/freecodecamp-proxy
      - docker push $DOCKER_USERNAME/freecodecamp-proxy
    - stage: build api docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t freecodecamp-api . -f Dockerfile.freecodecamp
      - docker images
      - docker tag freecodecamp-api $DOCKER_USERNAME/freecodecamp-api
      - docker push $DOCKER_USERNAME/freecodecamp-api