FROM nginx:1.15.8-alpine-perl

EXPOSE 80
EXPOSE 443

ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./nginx/snippets /etc/nginx/snippets
ADD ./nginx/sites-enabled /etc/nginx/sites-enabled
ADD ./www /var/www


RUN rm /etc/nginx/conf.d/default.conf
