version: '3'

services:
  proxy:
    image: bounceytaylor/freecodecamp-proxy
    ports:
      - 80:80
      - 443:443
    links:
      - 'freecodecamp:freecodecamp'
    volumes:
      - /etc/letsencrypt:/etc/ssl
      - ./www:/var/www
    environment:
      FORUM_PROXY_ADDRESS: http://your-server-ip

  freecodecamp:
    restart: always
    image: bounceytaylor/freecodecamp-api
    ports:
      - 3000:3000
    environment:
      PORT: 3000

      MONGOHQ_URL: 'mongodb://localhost:27017/freecodecamp'

      ROLLBAR_APP_ID: my-rollbar-app-id

      AUTH0_CLIENT_ID: appId
      AUTH0_CLIENT_SECRET: secret
      AUTH0_DOMAIN: my-domain.example.com

      SESSION_SECRET: secretstuff
      COOKIE_DOMAIN: .example.com
      COOKIE_SECRET: 'this is a secret'
      JWT_SECRET: 'a very long secret'

      STRIPE_PUBLIC: pk_from_stipe_dashboard
      STRIPE_SECRET: sk_from_stipe_dashboard

      PAYPAL_SUPPORTERS: 1703
      PEER: stuff
      DEBUG: null
      NODE_ENV: production
